### ISSUE TITLE
Memory leak Pointcloud update function

### ISSUE THREAD

**Issue by brgrp** [fzi-forschungszentrum-informatik/gpu-voxels#108]
Hi,

I found a small memory leak in the following member function (PointCloud.cu):
void update(const PointCloud* cloud);

Copy constructor works without any problems.

Any ideas? Thanks in advance.

NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2

**Comment by cjue** [comment]
Hi @codegrafix ,

thanks for the input. 

I am trying to fix this leak. Did you detect it with `cuda-memcheck`?
