### ISSUE TITLE
Hi I have a question about gpu-voxel

### ISSUE THREAD

**Issue by SookangJun** [fzi-forschungszentrum-informatik/gpu-voxels#18]
Hi this is Sookang Jun who is interested in your gpu-voxel system from Korea.

Actually, I saw a video on  "In this video we demonstrate the population of a GPU Octree with the Pointcloud data of two depth-cameras." which is third video on build a map with depth camera at http://www.gpu-voxels.org/multimedia/.

So, I have downloaded gpu-voxel-master zip folder in your git-up homepage.

However, I don't know how to execute for this.

If u teach me how to do this or teach me about manual on it, I really appreciate it. Thanx ：）

**Comment by Squelsh** [comment]
Hi Sookang Jun,

thanks for your interest. Did you have a look at the documentation pages and into the examples folder?
Check the code of "SweptVolumeVsEnvironment.cpp" in the examples folder.
Basically you create a GPU-Voxels map, instantiate a Kinect-Object, start a loop and insert the Kinect-Data into the map.

The Kinect object supports a "device-identifier", so you can instantiate it multiple times with different cameras. But I don't know how this works with Asus cameras or the newer Kinects that don't offer a serial number...

Please join the mailinglist and write there if you need more help, as this here is intended for bugs only.


Best,
Andreas
