### ISSUE TITLE
About   ...bin/ file in   ./octree_provider  ...?

### ISSUE THREAD

**Issue by NAMCER** [fzi-forschungszentrum-informatik/gpu-voxels#2]
Hi.
I want to see you run this command:
octree_provider -shm 0 -m kinect_live -resTree 20 -resFree 20 -resOcc 20 -mem 1024 -fps 30 -c -shm 1 -m load_pcd -f ./robot4cmRes.pcd -resTree 20 -resFree 20 -resOcc 20 -x 20 -y 180 -z -10

What kind of effect will be?  
I hope you can attach a picture ThankX.

**Comment by Squelsh** [comment]
Hi Namcer!

The line you posted will populate two Octrees, one with Kinect data and one with a static robot model. A collision check between both is executed.

Here is the screenshot.
![screenshot from 2015-03-11 19 16 51](https://cloud.githubusercontent.com/assets/898675/6603600/6df7f500-c823-11e4-82ff-33fc3c434966.png)

BUT: I have to admit that I forgot to update the according configfile for the viewer! So if you start the viewer with `packages/gpu_voxels/src/examples/Config_live_col_detect.xml` you will probably only see an empty scene.
Change the following at the end of the file, to see the scene:
```
<camera>
  <position>
    <x> 8314.02 </x>
    <y> 8697.94 </y>
    <z> 8211.91 </z>
  </position>
  <horizontal_angle> 341.519 </horizontal_angle> <!-- given in Deg -->
  <vertical_angle> 0.264989 </vertical_angle> <!-- given in Deg -->
  <field_of_view> 60 </field_of_view> <!-- given in Deg -->
</camera>
```
Also I just discovered the bug that the viewer will crash, if the Metavoxel-Size (Mousewheel) is too small ):

Hope that helps.
Andreas
