### ISSUE TITLE
List dependencies in README

### ISSUE THREAD

**Issue by vsimko** [fzi-forschungszentrum-informatik/gpu-voxels#21]
Could you list the dependencies inside README.
Now, we need to install packages according to cmake messages in a trial-and-error fashion.

**Comment by Squelsh** [comment]
Good point!
I'll do that after my holidays.

Until then, have a look at the Docu on GPU-Voxels.org. There is a list. Hope it is complete...

Cheers,
Andreas

**Comment by Squelsh** [comment]
Done in R0.9
