### ISSUE TITLE
cmake error at example_how_to_link

### ISSUE THREAD

**Issue by maxtom** [fzi-forschungszentrum-informatik/gpu-voxels#46]
I follow the setup instruction, and anything is ok, but when I try to test the example_how_to_link, I got the following errors:

-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
-- GVL include dirs are: /home/i/codebase/Topological-SLAM/gpu-voxels/packages/gpu_voxels/src
CMake Error at CMakeLists.txt:47 (target_link_libraries):
  The LINK_PUBLIC or LINK_PRIVATE option must appear as the second argument,
  just after the target name.

-- Configuring incomplete, errors occurred!

**Comment by Squelsh** [comment]
Hi Maxtom,

I never experienced this specific error message. Could you give me a bit more details? What OS are you using? Which CMake version? Perhaps I can recreate the error locally.

Cheers,
Andreas

**Comment by Squelsh** [comment]
Please give some more info. Otherwise I will close this issue.

**Comment by Squelsh** [comment]
Closed due to no further reaction.
