### ISSUE TITLE
What is the basic coordiante system in octree?

### ISSUE THREAD

**Issue by nangong** [fzi-forschungszentrum-informatik/gpu-voxels#51]
I found the function 
`
 void kernel_toVoxels(const Vector3f* input_points, size_t num_points, Vector3ui* output_voxels, float  voxel_side_length)
`
calculate the voxel coordinate by:
`
    voxel.x = uint32_t(pointf.x / voxel_side_length); // convert to meter and discrete in voxel
    voxel.y = uint32_t(pointf.y / voxel_side_length);  // convert to meter and discrete in voxel
    voxel.z = uint32_t(pointf.z / voxel_side_length);  // convert to meter and discrete in voxel
`
Does this mean I should preprocess all my pointcloud by minus the minimum (x,y,z).

**Comment by Squelsh** [comment]
This means that the Octree can not handle negative coordinates. 
For a sensor on a mobile base you should add a static offset to all your sensor points.
The offset must be large enough to ensure that even after moving your base into a negative direction, you must never experience negative measurement points.
