### ISSUE TITLE
Problem when building without PCL support

### ISSUE THREAD

**Issue by Squelsh** [fzi-forschungszentrum-informatik/gpu-voxels#61]
Hi,

the build fails if I build without PCL support.
Fortunately there are just some missing dependencies in the examples:
- shift_vs_transform misses PCL as an external dependency
- distance_kinect_demo misses PCL as an external dependency

Adding those fixes the probs.

**Comment by cjue** [comment]
Thanks, this will be addressed in the upcoming release.
