### ISSUE TITLE
Set visualization colors

### ISSUE THREAD

**Issue by bsaund** [fzi-forschungszentrum-informatik/gpu-voxels#66]
I am working with several MT_PROBAB_VOXELMAPs. Currently there are too many green voxels around the screen, so it is hard to see what is happening
Is there a way to:

1. Set a different visualization color for each map?

2. Set the opacity of each voxel based on the probability value?

**Comment by cjue** [comment]
Hi Brad,

1:
the first problem of using different colors for occupied voxels (usually type "1") can be solved as shown here with a Visualizer config. Just pass the XML config to the visualizer like this: "-c config.xml"
https://github.com/fzi-forschungszentrum-informatik/gpu-voxels/blob/master/packages/gpu_voxels/src/examples/VisConfig_RobotVsEnvironment.xml

Just give a different color definition for each map name you want to customize. There are several possible notations for the color of a voxel. Details on the available configuration options can be found here: https://github.com/fzi-forschungszentrum-informatik/gpu-voxels/blob/master/packages/gpu_voxels/src/gpu_visualization/XMLInterpreter.h

2:
The second task is a bit more problematic. It's generally possible to adapt the rendering of probabilistic voxels, but I would recommend using a color gradient for this instead. Our previous experiments with modified transparency values resulted in quite some visual glitches whenever there are overlapping voxels from multiple maps/lists/octrees.

**Comment by bsaund** [comment]
Thanks!
