### ISSUE TITLE
GPU-Voxels connected ROS

### ISSUE THREAD

**Issue by NAMCER** [fzi-forschungszentrum-informatik/gpu-voxels#7]
I want to see 3D-Visualizer.
So I installed  ROS RViz . But I do not know connected gpu-voxel.
I hope you can help me.
ThankX.

**Comment by Squelsh** [comment]
Hi Namcer,

no, I can not help you. 

Once again: THIS IS A BUGTRACKER! Not a forum for discussions. Please use the mailinglist for general questions!

Currently there is no connection between GPU-Voxels and ROS and there will never be one for the rviz Visualizer as it is unusable for CUDA. 

PLEASE READ THE DOCS on the website to see how to launch the visualizer.
http://www.gpu-voxels.org
