### ISSUE TITLE
Where is the gpu_voxels_visualizer????

### ISSUE THREAD

**Issue by Hooney1011** [fzi-forschungszentrum-informatik/gpu-voxels#8]
Hello.
First, I had compiled the gpu-voxels.
So build -> bin files are maked.
Files name are 

icl_core_performance_monitor_example
octree_bench
octree_provider
octree_test
robot_vs_environment
sandbox
swept_volume_vs_environment
test_gpu_voxels_core
test_icl_core_config
test_icl_core_convert
test_icl_core_logging
ts_icl_core
ts_icl_core_config
ts_icl_core_crypt
ts_icl_core_thread
uls

Total 16 files.

But I'm not found the gpu_voxels_visualizer file anywhere.
How to make the gpu_voxels_visualizer bin file???

Please give me the information!!!!!!!!
please!!!

Thank you.

**Comment by Squelsh** [comment]
Hi!

Seems that you did not install all the required libraries... So CMake
can not start the compilation.

Have a look at the Website to find a list of the Libs or look at the
output of CMake: It will tell you, why it can not build
gpu-voxels-visualizer.


GL,
Andreas
