### ISSUE TITLE
undefined reference to symbol '_ZN3ros10NodeHandle9subscribeERNS_16SubscribeOptionsE'

### ISSUE THREAD

**Issue by jlllweco** [fzi-forschungszentrum-informatik/gpu-voxels#81]
I am simply trying to compile a program in ROS. I already linked all the necessary libraries but this one I can't find. All I am getting is the following error in code blocks.
I have to modify `DistanceKinectDemo` and use it to get EDT MAP.

Anybody know how to get rid of this error? Or even which library it require?
Maybe there is something wrong with GPU-VOXEL and ROS....
Thank you so much for helping me.

`/usr/bin/ld:CMakeFiles/DistanceKinectDemo.dir/src/DistanceKinectDemo.cpp.o: undefined reference to symbol`

`_ZN3ros10NodeHandle9subscribeERNS_16SubscribeOptionsE`

`/opt/ros/kinetic/lib/libroscpp.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`
`gpuvoxelgetpointcloud/CMakeFiles/DistanceKinectDemo.dir/build.make:370: recipe for target 
'/home/pcl_gpu/devel/lib/gpuvoxelgetpointcloud/DistanceKinectDemo' failed`
`make[2]: *** [/home/shupeng/pcl_gpu/devel/lib/gpuvoxelgetpointcloud/DistanceKinectDemo] Error 1
CMakeFiles/Makefile2:1130: recipe for target `
`gpuvoxelgetpointcloud/CMakeFiles/DistanceKinectDemo.dir/all' failed`

**Comment by cjue** [comment]
Hi,

could you successfully compile and run the ROS examples, like tf_interface?

If so, did you add ROS to the icmaker dependencies in the CMakeLists, like this?
```
ICMAKER_EXTERNAL_DEPENDENCIES(
  ROS
  CUDA
  )
```
