### ISSUE TITLE
Hakcs for Ubuntu 18.04 with CUDA 9.2

### ISSUE THREAD

**Issue by Squelsh** [fzi-forschungszentrum-informatik/gpu-voxels#85]
I commited some quick and dirty hacks that were required to compile the master on Ubuntu 18.04 with CUDA 9.2.
You can find them in https://github.com/Squelsh/gpu-voxels/tree/quirks_for_18_04
I will not make a pull request, as those are hacks that need some rework in IcMaker.

This also requires a from-source version of the latest Eigen 3.3 branch, where some CUDA / Eigen incompatibilities about "half" datatypes and CUDA header includes were fixed.

Cheers,
Andy

**Comment by cjue** [comment]
These and other compatibility fixes are included in version 1.3.0
