### ISSUE TITLE
problem with Visualization of map

### ISSUE THREAD

**Issue by jlllweco** [fzi-forschungszentrum-informatik/gpu-voxels#87]
I'd like to draw a circle in the probability map and make the circle bigger. However, the problem is when the circle getting bigger, there seems to be a barrier in the map. Would you please help me with the problem?Thanks a lot!
the code is here

`Vector3ui map_dimensions(256, 256, 256);'
'const float voxel_side_length = 1;`
and the circle is 
```
//create a circle
pcl::PointCloud<pcl::PointXYZ>::Ptr circle(float x, float y, float z, double r, int numPoints)
{
    pcl::PointCloud<pcl::PointXYZ>::Ptr circlePtr (new pcl::PointCloud<pcl::PointXYZ>);

    if(r <= 0)
      return circlePtr;

    double interval = M_PI * 2 * r / numPoints, currTheta = 0;
    for (int i = 0; i < numPoints; i++, currTheta += interval)
    {
        pcl::PointXYZ currPt(x + r * cos(currTheta), y + r * sin(currTheta), z);
        circlePtr->push_back(currPt);
    }

    return circlePtr;
}
void get_radius_bigger(const ros::TimerEvent&)
{
    prob_map->clearMap();
    datas.clear();
    static double r = 5;
    int x, y, z, numPoints;
    x = y = z = 0;
    numPoints = 2000;
    r += 0.1;
    pcl::PointCloud<pcl::PointXYZ>::Ptr circlePtr = circle(x, y, z, r, numPoints);
   for (uint32_t i=0; i<circlePtr->size(); i++)
  {
     if (!std::isnan(circlePtr->points[i].z))`
      {
       Vector3f tmp(circlePtr->points[i].x+50, circlePtr->points[i].y+50, circlePtr->points[i].z+50);`
       datas.push_back(tmp);`
      }
  }
     ROS_INFO("RADIUS: %f\n", r);
     myKinectCloud.update(datas);
```

![screenshot from 2018-10-08 21-04-55](https://user-images.githubusercontent.com/36145675/46611281-efb82100-cb3f-11e8-9003-49de7cc6d0b6.png)

![screenshot from 2018-10-08 21-06-26](https://user-images.githubusercontent.com/36145675/46611269-e9c24000-cb3f-11e8-96a6-184f2170b06a.png)

 
The second question is what does different color,coordinates, and the scale in the visualization mean? Is there any documentation I can find out? Thanks a lot!

**Comment by Squelsh** [comment]
GPU-Voxels can not handle negative coordinates. Simple as that :)

The colors can be configured in the .xml files that you pass to the visualizer and their meaning differs from Map-Type to Map-Type. In general they represent probabilities or Bitvector-IDs but there are also exceptions, like collisions.

Have a look at the various VisualizerConfig files in the examples directory to get an overview.
https://github.com/fzi-forschungszentrum-informatik/gpu-voxels/blob/master/packages/gpu_voxels/src/examples/VisConfig_Probability.xml
There is also some documentation in the beginning of the files.

Apart from that: You don't have to use PCL pointclouds to play with artificial pointclouds.
We have data-types for that too. If you want to avoid conversion.
https://github.com/fzi-forschungszentrum-informatik/gpu-voxels/blob/bf4ed093d780822f6990d0097574f5c3f2f7d4ae/packages/gpu_voxels/src/gpu_voxels/helpers/PointCloud.h


Cheers,
Andreas

**Comment by cjue** [comment]
Closing the issue because it appears to be cleared up.

Please let me know if there are problems remaining.
