### ISSUE TITLE
Distance map parameter meaning

### ISSUE THREAD

**Issue by husong998** [fzi-forschungszentrum-informatik/gpu-voxels#88]
# Problem
I followed the example code of ProbMap2DistMap.cpp to try to generate a distance map for my own use case. My probability map is simply a single dot, shown as below:
![screenshot from 2018-10-15 19-33-36](https://user-images.githubusercontent.com/34832485/46949079-b8eb8900-d0b2-11e8-951d-39da739e4502.png)

However, the generated probability map does not make sense to me:
![screenshot from 2018-10-15 19-33-18](https://user-images.githubusercontent.com/34832485/46949109-d7ea1b00-d0b2-11e8-96a2-a4baf21ec005.png)

We expect the distance map to be somewhat cubical or spherecal. The planar shape is really counter intuitive. Can someone explain to me why is it so?

The code snippet used to generate the distance map is as follow:
```
 // but we generat the distance map only from voxels with an occupancy higher than 0.55, so this section gets not converted
boost::shared_ptr<DistanceVoxelMap> dist_map(gvl->getMap("myDistanceMap")->as<DistanceVoxelMap>());
  dist_map->mergeOccupied(prob_map, Vector3ui(0), 0.55);
  dist_map->parallelBanding3D(m1, m2, m3, PBA_DEFAULT_M1_BLOCK_SIZE, PBA_DEFAULT_M2_BLOCK_SIZE, PBA_DEFAULT_M3_BLOCK_SIZE, 1);
```
m1, m2, m3 are 1, 1, 4 respectively in this case
# Additianlly
What do the parameters of parallelBanding3D mean?
How is the occupancy value calculated in probability map?

Any help is appreciated.

**Comment by cjue** [comment]
Hi,
thank you for your report!

Could you please show me some more of your example code?

Does the initial DistanceVoxelMap after mergeOccupied look as expected, if you don't run the parallelBanding3D step?

What is printed when you left-click on of the visible voxels?

Did you enter one of the "slice modes" by pressing "t" in the visualizer?

Regarding PBA parameters: m1,m2 and m3 are ways to increase the parallelism during the distance computation - for almost all 3D scenarios it's fine to have them at their default values of 1. Setting m3 to 2 or 4 can increase performance a bit.

**Comment by cjue** [comment]
Hi again,

the ProbMap2DistMap example can be quite confusing, I will try to improve the comments in the file.

When you start the default example, you should see green voxels with an occupancy value of 0 (a probability of 0.5) and blue voxels with an occupancy of 125 (probability 0.992126). You can get this output on the visualizer commandline by left-clicking the voxels.

The example uses a threshold probability of 0.55 during the merge step, which will essentially cut out the "green" voxels.

Attached you can find the expected output for the Distance map. To get the correct rendering, right-click the visualizer and select "Render Moder > Distance Maps Rendermode > Multicolor gradient".

This should give you something like this: (the view is oriented towards the origin to show the gap on the backside of the cube.

![gpuvoxels_prob2distmap_hull](https://user-images.githubusercontent.com/20859666/48371865-30660580-e6bd-11e8-97e9-b819d97a486c.png)

You can also repeatedly use the "t" key to show just slices of the voxel data, like this:

![gpuvoxels_prob2distmap_slice](https://user-images.githubusercontent.com/20859666/48371866-30660580-e6bd-11e8-83fe-e8f67cf88118.png)

Does your example behave as expected if you inspect it like this?

**Comment by cjue** [comment]
Closing the issue beacause there was no reply. Please let me know if the problem still exists.
