### ISSUE TITLE
Version of Required Libraries (CUDA, PCL, and OpenNI) 

### ISSUE THREAD

**Issue by hclin77923** [fzi-forschungszentrum-informatik/gpu-voxels#89]
Hello,

I am a newbie in Ubuntu and open source society. GPU-voxel looks impressive, and I really want to try it. 
I understand from the website about the required libraries; however, I am not sure which version of each library I should install. 
For instance, the latest Cuda is 10.0 and the latest PCL is 1.9.0 (but I checked other issues, some people are using 1.8). Also, there is OpenNI and OpenNI2. 

I am using Ubuntu 16.04 and have installed Ros-Kinetic and boost 1.67.0 

Could you kindly provide the recommend version of those required library? I really appreciate your answer. Thank you!

**Comment by cjue** [comment]
Hi,
when you are using Ubuntu 16.04 and a complete ROS kinetic distribution (ros-kinetic-desktop-full), you automatically get most of these dependencies in a working version by default, like PCL and Boost.

I recommend to use CUDA 9.2. We have not yet tested Cuda 10.0, so there might be incompatibilities.

Let me know if you encounter any issues.
