### ISSUE TITLE
How to  using  two  kinect and insert point cloud function???

### ISSUE THREAD

**Issue by Hooney1011** [fzi-forschungszentrum-informatik/gpu-voxels#9]
Hi 

- I want to using  two kinects  launch  ./gpu_voxels_visualization -c Config_live_col_detect.xml?

- where is real-time insert point cloud function?

Please give me the info!!!

Thank you.

**Comment by Squelsh** [comment]
Hi!

Did you have a look into the example programs? There you will find code to get Kinect data into the maps.

BTW: This has absolutely nothing to do with the visualizer and its config file!

PLEASE use the mailing list for general questions like above! This is a BUGTRACKER!
