### ISSUE TITLE
OpenGL Mathematics error: GLSL 4.10  

### ISSUE THREAD

**Issue by arrfou90** [fzi-forschungszentrum-informatik/gpu-voxels#94]
Hi!
I want to report this incompatibility error. I get a runtime error when running  `"gpu_voxels_visualizer"`

```
<****-**-** **:**:**.***>  Visualization(Warning) Visualizer::initializeVisualizer: Couldn't open the shared memory segment of Visualizer!

<****-**-** **:**:**.***> Shader(Error)::loadShaders: 0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
```

My system:
**Ubuntu 18.04
CUDA 10.0 
Cuda_compute_cap:3.5
OpenGL version string: 3.0 Mesa 18.0.5**

Thanks,
Arrfou

**Comment by arrfou90** [comment]
I resolved it by reinstalling Nvidia driver! apparently I had broken links.

**Comment by cjue** [comment]
Thank you for reporting your solution :)

**Comment by dion-jy** [comment]
In my case, reinstallation was not enough..  Is anyone who has encountered it..?
